//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRSystemEntities : DbContext
    {
        public HRSystemEntities()
            : base("name=HRSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<t_config> t_config { get; set; }
        public DbSet<t_empleados> t_empleados { get; set; }
        public DbSet<t_metricos> t_metricos { get; set; }
        public DbSet<t_objetidet> t_objetidet { get; set; }
        public DbSet<t_objetivos> t_objetivos { get; set; }
        public DbSet<t_plantas> t_plantas { get; set; }
        public DbSet<t_usuarios> t_usuarios { get; set; }
    }
}
