//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_budget_pta
    {
        public string planta { get; set; }
        public decimal axo { get; set; }
        public Nullable<decimal> budget { get; set; }
        public string u_id { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        public virtual t_plantas t_plantas { get; set; }
    }
}
