//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_config
    {
        public string clave { get; set; }
        public string planta { get; set; }
        public string env_email { get; set; }
        public string server_mail { get; set; }
        public string send_email { get; set; }
        public string send_passwd { get; set; }
        public Nullable<decimal> port { get; set; }
        public string ind_html { get; set; }
        public string ind_ssl { get; set; }
        public string ind_alerta1 { get; set; }
        public string ind_alerta2 { get; set; }
        public string ind_alerta3 { get; set; }
        public string ind_alerta4 { get; set; }
        public string sys_path { get; set; }
        public string ind_emailtest { get; set; }
        public string test_email { get; set; }
    }
}
