//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_config_m4
    {
        public string clave { get; set; }
        public Nullable<System.DateTime> f_inicio { get; set; }
        public Nullable<System.DateTime> f_final { get; set; }
        public Nullable<decimal> cap_mrp { get; set; }
        public string ind_alerta1 { get; set; }
    }
}
