//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_config_m1
    {
        public string clave { get; set; }
        public Nullable<System.DateTime> f_objini { get; set; }
        public Nullable<System.DateTime> f_objfin { get; set; }
        public Nullable<decimal> axo_activo { get; set; }
        public Nullable<System.DateTime> f_evalini1 { get; set; }
        public Nullable<System.DateTime> f_evalfin1 { get; set; }
        public Nullable<System.DateTime> f_evalini2 { get; set; }
        public Nullable<System.DateTime> f_evalfin2 { get; set; }
        public Nullable<System.DateTime> f_califica { get; set; }
        public Nullable<System.DateTime> f_calificafin { get; set; }
    }
}
