//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_empleados()
        {
            this.t_objetivos = new HashSet<t_objetivos>();
            this.t_empleados1 = new HashSet<t_empleados>();
            this.t_merit = new HashSet<t_merit>();
            this.t_meridet = new HashSet<t_meridet>();
            this.t_merit1 = new HashSet<t_merit>();
        }
    
        public string empleado { get; set; }
        public string nombre { get; set; }
        public string supervisor { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
        public string planta { get; set; }
    
        public virtual t_plantas t_plantas { get; set; }
        public virtual t_usuarios t_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_objetivos> t_objetivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_empleados> t_empleados1 { get; set; }
        public virtual t_empleados t_empleados2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_merit> t_merit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_meridet> t_meridet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_merit> t_merit1 { get; set; }
    }
}
