//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_empleados
    {
        public t_empleados()
        {
            this.t_objetivos = new HashSet<t_objetivos>();
        }
    
        public string empleado { get; set; }
        public string nombre { get; set; }
        public string supervisor { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
        public string planta { get; set; }
    
        public virtual t_plantas t_plantas { get; set; }
        public virtual t_usuarios t_usuarios { get; set; }
        public virtual ICollection<t_objetivos> t_objetivos { get; set; }
    }
}
