//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_meridet
    {
        public string supervisor { get; set; }
        public decimal axo { get; set; }
        public string empleado { get; set; }
        public string nombre { get; set; }
        public string ind_elegible { get; set; }
        public string jobcode { get; set; }
        public string puesto { get; set; }
        public string calificacion { get; set; }
        public Nullable<decimal> salario_axo { get; set; }
        public Nullable<decimal> budget_porc { get; set; }
        public Nullable<decimal> sugerido_imp { get; set; }
        public Nullable<decimal> sugerido_porc { get; set; }
        public Nullable<decimal> lump_imp { get; set; }
        public Nullable<decimal> lump_porc { get; set; }
        public Nullable<decimal> salario_nuevo { get; set; }
        public Nullable<decimal> market_mcr { get; set; }
        public string merit_guide { get; set; }
        public string estatus { get; set; }
        public string nota { get; set; }
        public string out_guide { get; set; }
        public string u_id { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        public virtual t_califica t_califica { get; set; }
        public virtual t_empleados t_empleados { get; set; }
        public virtual t_jobcode t_jobcode { get; set; }
        public virtual t_merit t_merit { get; set; }
    }
}
