//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_metricos
    {
        public t_metricos()
        {
            this.t_objetidet = new HashSet<t_objetidet>();
        }
    
        public string metrico { get; set; }
        public string descrip { get; set; }
    
        public virtual ICollection<t_objetidet> t_objetidet { get; set; }
    }
}
