//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_merit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_merit()
        {
            this.t_meridet = new HashSet<t_meridet>();
        }
    
        public string supervisor { get; set; }
        public decimal axo { get; set; }
        public string nombre { get; set; }
        public string depto { get; set; }
        public Nullable<decimal> budget_imp { get; set; }
        public Nullable<decimal> budget_porc { get; set; }
        public Nullable<decimal> budget_spen { get; set; }
        public string estatus { get; set; }
        public string notas { get; set; }
        public string u_id { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
        public string autoriza { get; set; }
        public string ind_autoriza { get; set; }
        public Nullable<System.DateTime> f_autoriza { get; set; }
        public string n_autoriza { get; set; }
    
        public virtual t_empleados t_empleados { get; set; }
        public virtual t_empleados t_empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_meridet> t_meridet { get; set; }
    }
}
