//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_objetivos
    {
        public t_objetivos()
        {
            this.t_objetidet = new HashSet<t_objetidet>();
        }
    
        public string planta { get; set; }
        public decimal folio { get; set; }
        public string empleado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> axo { get; set; }
        public string estatus { get; set; }
        public string aprobado { get; set; }
        public Nullable<System.DateTime> f_aprobado { get; set; }
        public string revision1 { get; set; }
        public string nota_r1 { get; set; }
        public Nullable<System.DateTime> f_r1 { get; set; }
        public string revision2 { get; set; }
        public string nota_r2 { get; set; }
        public Nullable<System.DateTime> f_r2 { get; set; }
        public string calificacion { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        public virtual t_empleados t_empleados { get; set; }
        public virtual ICollection<t_objetidet> t_objetidet { get; set; }
        public virtual t_plantas t_plantas { get; set; }
    }
}
