//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_objetidet
    {
        public string empleado { get; set; }
        public decimal axo { get; set; }
        public decimal consec { get; set; }
        public string planta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string objetivo { get; set; }
        public string descrip { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string metrico { get; set; }
        public string cancelado { get; set; }
        public string nota_cancel { get; set; }
        public Nullable<System.DateTime> f_cancel { get; set; }
        public string u_cancel { get; set; }
        public Nullable<decimal> resultado1 { get; set; }
        public string nota_r1 { get; set; }
        public Nullable<System.DateTime> f_r1 { get; set; }
        public Nullable<decimal> resultado2 { get; set; }
        public string nota_r2 { get; set; }
        public Nullable<System.DateTime> f_r2 { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        public virtual t_metricos t_metricos { get; set; }
        public virtual t_plantas t_plantas { get; set; }
        public virtual t_objetivos t_objetivos { get; set; }
    }
}
