//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_plantas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_plantas()
        {
            this.t_empleados = new HashSet<t_empleados>();
            this.t_usuarios = new HashSet<t_usuarios>();
            this.t_objetidet = new HashSet<t_objetidet>();
            this.t_objetivos = new HashSet<t_objetivos>();
            this.t_budget_pta = new HashSet<t_budget_pta>();
        }
    
        public string planta { get; set; }
        public string nombre { get; set; }
        public string servidor { get; set; }
        public string instancia_sql { get; set; }
        public string nombre_bd { get; set; }
        public string usuario_bd { get; set; }
        public string password_bd { get; set; }
        public string direct_email { get; set; }
        public string gte_email { get; set; }
        public string gte_email2 { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_empleados> t_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_usuarios> t_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_objetidet> t_objetidet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_objetivos> t_objetivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_budget_pta> t_budget_pta { get; set; }
    }
}
