//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_plantas
    {
        public t_plantas()
        {
            this.t_empleados = new HashSet<t_empleados>();
            this.t_objetivos = new HashSet<t_objetivos>();
            this.t_usuarios = new HashSet<t_usuarios>();
        }
    
        public string planta { get; set; }
        public string nombre { get; set; }
        public string servidor { get; set; }
        public string instancia_sql { get; set; }
        public string nombre_bd { get; set; }
        public string usuario_bd { get; set; }
        public string password_bd { get; set; }
        public string direct_email { get; set; }
        public string gte_email { get; set; }
        public string gte_email2 { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        public virtual ICollection<t_empleados> t_empleados { get; set; }
        public virtual ICollection<t_objetivos> t_objetivos { get; set; }
        public virtual ICollection<t_usuarios> t_usuarios { get; set; }
    }
}
