//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_usuarios()
        {
            this.t_empleados = new HashSet<t_empleados>();
            this.t_plantas1 = new HashSet<t_plantas>();
        }
    
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string planta { get; set; }
        public string email { get; set; }
        public string activo { get; set; }
        public string rol { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_empleados> t_empleados { get; set; }
        public virtual t_plantas t_plantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_plantas> t_plantas1 { get; set; }
    }
}
